language: php
php:
  - 5.4
  - 5.3

before_install:
  - git clone --depth=50 --branch=dev git://github.com/dim-s/regenix.git tmp
  - cp -R * tmp/modules/mymodule~ver
  - cd tmp/
  - git submodule init
  - git submodule update
  - chmod +x regenix

script: ./tmp/regenix test --module=mongodb~ver