language: php
php:
  - 5.4
  - 5.3

before_install:
  - mkdir -p regenix/modules/mymodule~ver
  - cp -R * regenix/modules/mymodule~ver
  - git clone --depth=50 --branch=dev git://github.com/dim-s/regenix.git
  - cd regenix/
  - git submodule update --init --recursive
  - chmod +x regenix

script: ./regenix/regenix test --module=mongodb~ver