language: php
php:
  - 5.4
  - 5.3

before_install:
  - shopt -s extglob
  - mkdir -p regenix/modules/mymodule~ver
  - cp -r !(regenix) regenix/module/mymodule~ver
  - git clone --depth=50 --branch=dev git://github.com/dim-s/regenix.git
  - cd regenix/
  - git submodule update --init --recursive
  - chmod +x regenix

script: ./regenix/regenix test --module=mongodb~ver