language: php
php:
  - 5.4
  - 5.3

before_install:
  - git clone --depth=50 --branch=dev git://github.com/dim-s/regenix.git
  - mkdir -p regenix/modules/mongodb~test
  - rsync -av --progress --exclude='regenix' ./ regenix/modules/mongodb~test
  - cd regenix/
  - git submodule update --init --recursive
  - chmod +x regenix

script: ./regenix test -module=mongodb~test
